/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import java.applet.AudioClip;


/**
 *
 * @author Personal
 */
public class OpcionesColores extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesColores
     */
    
    private static ActionListener listener;
    private static AudioClip sonido;
    
    
    public OpcionesColores(ActionListener listener) {
        initComponents();
        this.listener = listener;
        botonCambiarAmarillo1.addActionListener(listener);
        botonCambiarVerde1.addActionListener(listener);
        botonCambiarAzul1.addActionListener(listener);
        botonCambiarRojo.addActionListener(listener);
        inicializarImagen();
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Musica/Crash-selectColor.wav"));
        sonido.play();
    }
    
    public void inicializarImagen(){
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/punto.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon imagen;
        // Creo la imagen de fondo rojo.
        imagen = new ImageIcon(this.getClass().getResource("/Imagenes/FondoNegroUno.jpg"));
        JLabel fondo= new JLabel(); 
        fondo.setIcon(imagen);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, imagen.getIconWidth(), imagen.getIconHeight());
        this.add(fondo, BorderLayout.CENTER);
        this.setSize(fondo.getWidth(), fondo.getHeight());
    }
    
    public void actualizarPantalla(){ 
        this.update(this.getGraphics());
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rojoLabel1 = new javax.swing.JLabel();
        botonCambiarRojo = new javax.swing.JButton();
        verdeLabel = new javax.swing.JLabel();
        amarilloLabel1 = new javax.swing.JLabel();
        botonCambiarVerde1 = new javax.swing.JButton();
        botonCambiarAzul1 = new javax.swing.JButton();
        azulLabel1 = new javax.swing.JLabel();
        botonCambiarAmarillo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        rojoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rojo.PNG"))); // NOI18N
        rojoLabel1.setOpaque(true);

        botonCambiarRojo.setBackground(new java.awt.Color(102, 204, 255));
        botonCambiarRojo.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        botonCambiarRojo.setText("Rojo");
        botonCambiarRojo.setToolTipText("");
        botonCambiarRojo.setFocusable(false);
        botonCambiarRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarRojoActionPerformed(evt);
            }
        });

        verdeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Verde.PNG"))); // NOI18N

        amarilloLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Azul.png"))); // NOI18N

        botonCambiarVerde1.setBackground(new java.awt.Color(102, 204, 255));
        botonCambiarVerde1.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        botonCambiarVerde1.setText("Verde");
        botonCambiarVerde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarVerde1ActionPerformed(evt);
            }
        });

        botonCambiarAzul1.setBackground(new java.awt.Color(51, 204, 255));
        botonCambiarAzul1.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        botonCambiarAzul1.setText("Azul");
        botonCambiarAzul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarAzul1ActionPerformed(evt);
            }
        });

        azulLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Amarillo.png"))); // NOI18N

        botonCambiarAmarillo1.setBackground(new java.awt.Color(51, 204, 255));
        botonCambiarAmarillo1.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        botonCambiarAmarillo1.setText("Amarillo");
        botonCambiarAmarillo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarAmarillo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rojoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCambiarRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verdeLabel)
                    .addComponent(botonCambiarVerde1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amarilloLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCambiarAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(azulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCambiarAmarillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rojoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verdeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amarilloLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(azulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCambiarRojo)
                    .addComponent(botonCambiarAzul1)
                    .addComponent(botonCambiarVerde1)
                    .addComponent(botonCambiarAmarillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCambiarRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarRojoActionPerformed
        this.listener.actionPerformed(evt);
    }//GEN-LAST:event_botonCambiarRojoActionPerformed

    private void botonCambiarVerde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarVerde1ActionPerformed
        this.listener.actionPerformed(evt);
    }//GEN-LAST:event_botonCambiarVerde1ActionPerformed

    private void botonCambiarAzul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarAzul1ActionPerformed
        this.listener.actionPerformed(evt);
    }//GEN-LAST:event_botonCambiarAzul1ActionPerformed

    private void botonCambiarAmarillo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarAmarillo1ActionPerformed
        this.listener.actionPerformed(evt);
    }//GEN-LAST:event_botonCambiarAmarillo1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amarilloLabel1;
    private javax.swing.JLabel azulLabel1;
    private javax.swing.JButton botonCambiarAmarillo1;
    private javax.swing.JButton botonCambiarAzul1;
    private javax.swing.JButton botonCambiarRojo;
    private javax.swing.JButton botonCambiarVerde1;
    private javax.swing.JLabel rojoLabel1;
    private javax.swing.JLabel verdeLabel;
    // End of variables declaration//GEN-END:variables
}
